import React, { useEffect, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { money } from './dashboardData.js';

function Login({ onSuccess, lockedMessage }) {
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  async function submit(event) {
    event.preventDefault(); setBusy(true); setError('');
    try {
      const response = await fetch('/api/login', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) });
      const result = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(result.message || 'Access denied.');
      setPassword(''); onSuccess();
    } catch (err) { setError(err.message); } finally { setBusy(false); }
  }
  return <main className="login-shell"><section className="login-card"><a className="brand" href="/"><span className="brand-mark">NS</span><span><strong>Next Steps</strong><small>Secure owner portal</small></span></a><div><p className="eyebrow">Restricted access</p><h1>Owner operating dashboard</h1><p>The owner view is served only after server-side authentication. The password and signing secret are environment variables and are never stored in the browser application or repository.</p></div>{lockedMessage && <div className="secure-warning"><strong>Portal locked by design.</strong><p>{lockedMessage}</p></div>}<form onSubmit={submit}><label htmlFor="owner-password">Owner password</label><input id="owner-password" type="password" autoComplete="current-password" value={password} onChange={(event)=>setPassword(event.target.value)} required maxLength={256}/><button type="submit" disabled={busy || Boolean(lockedMessage)}>{busy?'Verifying…':'Enter secure portal'}</button></form>{error && <p className="form-error" role="alert">{error}</p>}<a href="/">Return to public dashboard</a></section></main>;
}

function PrivateKpi({ label, value, detail, warning }) { return <article className={warning?'private-kpi warning':'private-kpi'}><span>{label}</span><strong>{value}</strong><p>{detail}</p></article>; }

function OwnerView({ data, onLogout }) {
  const revenueVariance = data.financial.actualRevenueToDate - data.financial.plannedRevenueToDate;
  const drawVariance = data.financial.actualOwnerDrawToDate - data.financial.requiredOwnerDrawToDate;
  const funnel = [
    { stage: 'Qualified', value: data.pipeline.qualifiedProspects }, { stage: 'Contacted', value: data.pipeline.contacted },
    { stage: 'Discovery', value: data.pipeline.discoveryCalls }, { stage: 'Proposals', value: data.pipeline.proposals },
    { stage: 'Paid starters', value: data.pipeline.paidStarters }, { stage: 'Retainers', value: data.pipeline.activeRetainers },
  ];
  return <div className="owner-shell"><header className="owner-header"><a className="brand" href="/"><span className="brand-mark">NS</span><span><strong>Next Steps</strong><small>Owner operating dashboard</small></span></a><div><span>Protected session</span><button type="button" onClick={onLogout}>Sign out</button></div></header><main><div className="private-status"><span><strong>Fiscal year:</strong> {data.meta.currentFiscalYear}</span><span><strong>As of:</strong> {data.meta.asOf}</span><span><strong>Source:</strong> {data.meta.sourceMode}</span><span><strong>Cache:</strong> No-store</span></div>
  <section className="owner-hero"><div><p className="eyebrow">Private management view</p><h1>Operate from facts, not hope.</h1><p>Revenue, draw, cash, pipeline, compliance, and corrective action belong in one monthly decision system.</p></div><aside><span>Overall status</span><strong>{data.meta.overallStatus}</strong><p>{data.meta.statusExplanation}</p></aside></section>
  <section className="private-kpi-grid"><PrivateKpi label="Revenue to date" value={money.format(data.financial.actualRevenueToDate)} detail={`Plan: ${money.format(data.financial.plannedRevenueToDate)}`} warning={revenueVariance<0}/><PrivateKpi label="Revenue variance" value={money.format(revenueVariance)} detail={revenueVariance<0?'Below plan—corrective selling action required.':'At or above plan.'} warning={revenueVariance<0}/><PrivateKpi label="Owner draw paid" value={money.format(data.financial.actualOwnerDrawToDate)} detail={`Required: ${money.format(data.financial.requiredOwnerDrawToDate)}`} warning={drawVariance<0}/><PrivateKpi label="Outside-income bridge" value={money.format(data.financial.outsideIncomeUsed)} detail="Must be explicit whenever business cash cannot fund the required draw." warning={data.financial.outsideIncomeUsed>0}/><PrivateKpi label="Ending business cash" value={money.format(data.financial.endingCash)} detail={`Minimum reserve: ${money.format(data.financial.minimumCashReserve)}`} warning={data.financial.endingCash<data.financial.minimumCashReserve}/><PrivateKpi label="Active retainers" value={data.pipeline.activeRetainers} detail={`First-year target: ${data.pipeline.retainerTarget}`} warning={data.pipeline.activeRetainers<data.pipeline.currentMonthRetainerTarget}/></section>
  <section className="private-section"><div className="private-section-title"><p className="eyebrow">Financial monitoring</p><h2>Forecasts must surrender to monthly actuals.</h2><p>Zeros and blanks remain visible. The dashboard does not manufacture progress.</p></div><div className="private-chart-grid"><article className="private-chart-card"><h3>Revenue plan versus actual</h3><ResponsiveContainer width="100%" height={330}><LineChart data={data.financial.monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={(v)=>`$${Math.round(v/1000)}k`}/><Tooltip formatter={(v)=>money.format(v)}/><Legend/><Line dataKey="plan" name="Plan" stroke="#123f5a" strokeWidth={3}/><Line dataKey="actual" name="Actual" stroke="#cf9d3a" strokeWidth={3} connectNulls={false}/></LineChart></ResponsiveContainer></article><article className="private-chart-card"><h3>Owner draw plan versus actual</h3><ResponsiveContainer width="100%" height={330}><BarChart data={data.financial.monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={(v)=>`$${Math.round(v/1000)}k`}/><Tooltip formatter={(v)=>money.format(v)}/><Legend/><Bar dataKey="requiredDraw" name="Required draw" fill="#cf9d3a"/><Bar dataKey="actualDraw" name="Actual draw" fill="#2f7d7b"/></BarChart></ResponsiveContainer></article></div></section>
  <section className="private-section"><div className="private-section-title"><p className="eyebrow">Sales pipeline</p><h2>Activity must convert into paid proof.</h2></div><div className="private-chart-grid"><article className="private-chart-card"><h3>Current funnel totals</h3><ResponsiveContainer width="100%" height={330}><BarChart data={funnel} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="stage" width={100}/><Tooltip/><Bar dataKey="value" name="Count" fill="#123f5a" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></article><article className="pipeline-actions"><h3>Weekly required activity</h3>{Object.entries(data.pipeline.weeklyTargets).map(([label,target])=><p key={label}><span>{label.replace(/([A-Z])/g,' $1')}</span><strong>{target}</strong></p>)}<div className="pipeline-note"><strong>Management judgment</strong><p>{data.pipeline.managementNote}</p></div></article></div></section>
  <section className="private-section"><div className="private-section-title"><p className="eyebrow">Compliance and professional gates</p><h2>Operational success does not excuse missed legal, tax, insurance, cybersecurity, or SEAP obligations.</h2></div><div className="compliance-grid"><article><h3>Training status</h3><dl><div><dt>Logged</dt><dd>{data.training.loggedHours.toFixed(2)} hours</dd></div><div><dt>Verified / eligible</dt><dd>{data.training.verifiedHours.toFixed(2)} hours</dd></div><div><dt>Required</dt><dd>{data.training.totalRequiredHours} hours</dd></div></dl><p>{data.training.note}</p></article><article><h3>Open deadlines</h3>{data.compliance.deadlines.map((item)=><div className="deadline" key={item.date}><span>{item.date}</span><div><strong>{item.item}</strong><p>{item.status}</p></div></div>)}</article><article><h3>Professional review gates</h3>{data.professionalGates.map((item)=><div className="gate" key={item.name}><span>{item.status}</span><div><strong>{item.name}</strong><p>{item.action}</p></div></div>)}</article></div></section>
  <section className="private-section"><div className="private-section-title"><p className="eyebrow">Corrective action</p><h2>What must happen next.</h2></div><div className="action-grid"><article><h3>Priority actions</h3><ol>{data.actions.map((item)=><li key={item}>{item}</li>)}</ol></article><article><h3>Current alerts</h3>{data.alerts.map((item)=><div className={`alert ${item.level}`} key={item.message}><strong>{item.level}</strong><p>{item.message}</p></div>)}</article><article><h3>Data sources</h3>{data.dataSources.map((item)=><p key={item.name}><span>{item.name}</span><strong>{item.status}</strong></p>)}</article></div></section>
  </main><footer className="owner-footer"><strong>Confidential owner view</strong><p>No bank credentials, Social Security numbers, client names, or account-level transactions are stored in the browser application.</p></footer></div>;
}

export default function OwnerPortal() {
  const [state,setState]=useState({loading:true,authenticated:false,data:null,lockedMessage:''});
  async function load(){setState((s)=>({...s,loading:true}));try{const sessionResponse=await fetch('/api/session',{credentials:'same-origin',cache:'no-store'});const session=await sessionResponse.json().catch(()=>({}));if(sessionResponse.status===503){setState({loading:false,authenticated:false,data:null,lockedMessage:session.message||'Secure environment variables have not been configured.'});return;}if(!sessionResponse.ok||!session.authenticated){setState({loading:false,authenticated:false,data:null,lockedMessage:''});return;}const response=await fetch('/api/private-data',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw new Error('Protected data could not be loaded.');setState({loading:false,authenticated:true,data:await response.json(),lockedMessage:''});}catch(error){setState({loading:false,authenticated:false,data:null,lockedMessage:error.message});}}
  useEffect(()=>{load();},[]);
  async function logout(){await fetch('/api/logout',{method:'POST',credentials:'same-origin'});setState({loading:false,authenticated:false,data:null,lockedMessage:''});}
  if(state.loading)return <main className="loading-screen">Verifying secure session…</main>;
  if(!state.authenticated)return <Login onSuccess={load} lockedMessage={state.lockedMessage}/>;
  return <OwnerView data={state.data} onLogout={logout}/>;
}
