const el=id=>document.getElementById(id);
const tasks=()=>Object.fromEntries([...document.querySelectorAll('[data-task]')].map(x=>[x.dataset.task,x.checked]));
let plan={};
function payload(action='save'){const date=el('date').value;return{action,recordId:`DAS-${date}`,date,status:action==='close'?'Closed':'Open',objective:el('objective').value,plannedStart:el('plannedStart').value,plannedEnd:el('plannedEnd').value,actualStart:el('actualStart').value,actualEnd:el('actualEnd').value,breakMinutes:Number(el('breakMinutes').value||0),workHours:Number(el('hours').value||0),taskStatus:{...tasks(),_plan:plan},contactsSent:Number(el('contacts').value||0),responses:Number(el('responses').value||0),meetingsSet:Number(el('meetings').value||0),prospectingHours:Number(el('prospecting').value||0),followUpNotes:el('followUp').value,closeoutComments:el('comments').value,tomorrowFirstAction:el('tomorrow').value};}
function cards(){el('contactCard').textContent=el('contacts').value||0;el('responseCard').textContent=el('responses').value||0;el('meetingCard').textContent=el('meetings').value||0;}
function text(id,value){if(el(id))el(id).textContent=value||'';}
function renderPlan(p={}){plan=p;text('workspaceTitle',p.workspace?.title||'Open the required operating workspace');text('workspaceCopy',p.workspace?.copy);for(const lane of ['revenue','build','compliance']){text(`${lane}Title`,p[lane]?.title);text(`${lane}Copy`,p[lane]?.copy)}text('recordTitle',p.record?.title||'Record and synchronize every result');text('recordCopy',p.record?.copy);text('followTitle',p.followUp?.title);text('followCopy',p.followUp?.copy);text('respondTitle',p.followUp?.respondTitle);text('respondCopy',p.followUp?.respondCopy);text('prepareTitle',p.followUp?.prepareTitle);text('prepareCopy',p.followUp?.prepareCopy)}
function apply(r){document.querySelectorAll('[data-task]').forEach(x=>x.checked=false);['date','objective','plannedStart','plannedEnd','actualStart','actualEnd'].forEach(k=>{if(el(k)&&r[k]!=null)el(k).value=r[k]});el('hours').value=r.workHours||0;el('breakMinutes').value=r.breakMinutes||0;el('contacts').value=r.contactsSent||0;el('responses').value=r.responses||0;el('meetings').value=r.meetingsSet||0;el('prospecting').value=r.prospectingHours||0;el('followUp').value=r.followUpNotes||'';el('comments').value=r.closeoutComments||'';el('tomorrow').value=r.tomorrowFirstAction||'';const s=r.taskStatus||{};Object.entries(s).forEach(([k,v])=>{if(k==='_plan')return;const x=document.querySelector(`[data-task="${k}"]`);if(x)x.checked=!!v});renderPlan(s._plan||{});cards()}
function status(t,c=''){el('status').textContent=t;el('status').className=`status ${c}`}
async function load(){try{const r=await fetch('/api/action-sheet',{credentials:'same-origin',cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.message);apply(b.record);status(b.source==='created'?'A new action sheet was created from the current roadmap. All tasks and totals were reset.':'Today’s active action sheet loaded.','ok')}catch(e){status(e.message,'warn')}}
async function send(action){if(action==='close'&&!confirm('Close, archive, and retire this sheet? A new sheet will be generated from the current roadmap with all tasks and daily totals reset.'))return;status(action==='close'?'Closing and regenerating the action sheet…':'Saving progress…');try{const r=await fetch('/api/action-sheet',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(action))});const b=await r.json();if(!r.ok)throw new Error(b.message);apply(b.record);status(b.message,'ok')}catch(e){status(e.message,'warn')}}
['contacts','responses','meetings'].forEach(id=>el(id).addEventListener('input',cards));el('save').onclick=()=>send('save');el('close').onclick=()=>send('close');load();